#Default env
env=int

# Environment URLs
petstore.base.url=https://petstore.swagger.io/v2
petstore.ui.url=https://petstore.swagger.io/

# Environment URLs
int_url1=https://petstore.swagger.io/v2
uat_url1=https://uat-petstore.swagger.io/v2
prod_url1=https://api.petstore.com/v2

#for testing
# Environment URLs
int_url=https://petstore.swagger.io/v2
uat_url=https://petstore.swagger.io/v2
prod_url=https://petstore.swagger.io/v2

# Browser Config
browser=chrome
timeout=10