name: Petstore API and UI Automation

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run Automation Tests
      # We use -Dtest to specify your runner and -Dcucumber.filter.tags to focus
      run: mvn clean test -Dtest=com.petstore.Runner -Dcucumber.filter.tags="@regression"

    - name: Upload Cucumber Report
      if: always() # Upload reports even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-html-report
        path: target/cucumber-reports.html